// Offline fallback used when ANTHROPIC_API_KEY isn't configured, so the
// full generate -> practice -> export flow works end-to-end with zero
// external cost/setup. Clearly labeled as sample content rather than
// pretending to be real AI output — once a real key is added, /api/generate
// switches back to calling Anthropic automatically.
import { TRACK_LABELS, type Track, type QuestionCategory } from "@/lib/types";
import type { LlmPack } from "@/lib/validation";

function snippet(text: string, max = 140): string {
  const line = text
    .split(/\n|(?<=[.!?])\s/)
    .map((s) => s.trim())
    .find((s) => s.length > 20);
  return (line ?? text.trim()).slice(0, max);
}

export function buildMockPack(input: {
  track: Track;
  company?: string;
  jdText: string;
  resumeText: string;
}): LlmPack {
  const trackLabel = TRACK_LABELS[input.track];
  const co = input.company?.trim() || "this company";
  const jdBit = snippet(input.jdText);
  const resumeBit = snippet(input.resumeText);

  const fitSummary =
    `[Sample pack — no ANTHROPIC_API_KEY configured, so this wasn't generated by AI] ` +
    `For the ${trackLabel} role at ${co}, your resume suggests relevant groundwork worth ` +
    `stating plainly in the interview rather than assuming the interviewer connects the dots. ` +
    `The JD leans on points like "${jdBit}" — be ready to map your own experience to that ` +
    `directly. Add a real ANTHROPIC_API_KEY to get a fit summary actually tailored to your JD ` +
    `and resume text instead of this placeholder.`;

  const gaps: LlmPack["gaps"] = [
    {
      gap: "This is placeholder content, not a real gap analysis of your resume against the JD.",
      handleIt:
        "Set ANTHROPIC_API_KEY in your environment to get gaps identified from your actual pasted text.",
    },
    {
      gap: `Depth of hands-on ${trackLabel.toLowerCase()} experience relative to what the JD implies.`,
      handleIt:
        "Prepare one or two concrete examples that show direct exposure, even if the scope was smaller than the role calls for.",
    },
    {
      gap: "Quantified impact isn't obvious from a resume snippet alone.",
      handleIt:
        "Have 2-3 metrics ready (%, revenue, time saved) for your strongest project before the interview.",
    },
  ];

  const bank: Record<QuestionCategory, { question: string; testing: string; skeleton: string[] }[]> = {
    resume: [
      {
        question: `Walk me through "${resumeBit}" — what was your specific role versus the team's?`,
        testing: "Whether you can separate personal contribution from team output.",
        skeleton: ["Context: team size and your title", "Your specific ownership", "One decision you made unilaterally", "Outcome, quantified if possible"],
      },
      {
        question: "Which line on your resume are you least prepared to defend in detail, and why?",
        testing: "Self-awareness and honesty under scrutiny.",
        skeleton: ["Name the item honestly", "Why it's thinner than it reads", "What you'd say if pressed"],
      },
      {
        question: "Pick the most impressive metric on your resume — how was it actually calculated?",
        testing: "Whether resume numbers survive a follow-up question.",
        skeleton: ["Restate the metric", "Data source and calculation method", "Caveats you'd volunteer proactively"],
      },
      {
        question: "What's a resume bullet you'd write differently today, and how?",
        testing: "Growth and reflective thinking about your own work.",
        skeleton: ["Original bullet", "What you'd change", "What you learned since"],
      },
    ],
    functional: [
      {
        question: `What do you think this ${trackLabel.toLowerCase()} role actually needs in the first 90 days?`,
        testing: "Whether you read the JD closely and formed a real point of view.",
        skeleton: ["Top 1-2 JD requirements you'd prioritize first", "Why those first", "What 'done' looks like at day 90"],
      },
      {
        question: `Which part of ${co}'s current strategy would you push back on, if any?`,
        testing: "Independent thinking versus reflexive agreement.",
        skeleton: ["What you'd question and why", "Evidence or reasoning", "How you'd raise it constructively"],
      },
      {
        question: "How would you prioritize between two equally urgent asks from different stakeholders?",
        testing: "Structured prioritization under real constraints.",
        skeleton: ["Criteria you'd use to compare them", "Who you'd loop in", "What you'd communicate to the deprioritized side"],
      },
      {
        question: "What's a tool, framework, or metric from this domain you'd want to introduce here?",
        testing: "Domain fluency beyond what's on the resume.",
        skeleton: ["What it is, briefly", "Why it fits this specific role", "Risk of introducing it"],
      },
    ],
    behavioral: [
      {
        question: "Tell me about a time you disagreed with your manager's decision.",
        testing: "How you handle authority and disagreement professionally.",
        skeleton: ["Situation", "Task", "Action — how you raised it", "Result and what changed (or didn't)"],
      },
      {
        question: "Describe a time you had to deliver bad news to a stakeholder.",
        testing: "Communication under pressure and ownership of setbacks.",
        skeleton: ["Situation", "Task", "Action — how you framed it", "Result and follow-up"],
      },
      {
        question: "Tell me about a project that failed, and what you did next.",
        testing: "Resilience and honest accountability.",
        skeleton: ["Situation", "Task", "Action — what went wrong and your response", "Result and lesson applied since"],
      },
      {
        question: "Describe a time you had to influence someone without formal authority over them.",
        testing: "Persuasion and cross-functional collaboration.",
        skeleton: ["Situation", "Task", "Action — your approach to influence", "Result"],
      },
    ],
    curveball: [
      {
        question: `If ${co} had to cut its ${trackLabel.toLowerCase()} budget by 30% tomorrow, what's the first thing you'd protect?`,
        testing: "Judgment under constraint, not just optimism.",
        skeleton: ["What you'd protect and why", "What you'd cut first", "Risk you're accepting"],
      },
      {
        question: "Estimate how many people in this city could plausibly be a customer of this company.",
        testing: "Structured estimation under ambiguity.",
        skeleton: ["Stated assumptions", "Breakdown into segments", "Rough final number with sanity check"],
      },
      {
        question: "What would make you quit this role within the first six months?",
        testing: "Self-awareness about fit and honesty about deal-breakers.",
        skeleton: ["Name 1-2 real deal-breakers", "Why those specifically", "What you'd need to see instead"],
      },
    ],
  };

  const questions: LlmPack["questions"] = (
    ["resume", "functional", "behavioral", "curveball"] as QuestionCategory[]
  ).flatMap((category) => bank[category].map((q) => ({ category, ...q })));

  const askThem: LlmPack["askThem"] = [
    `What does success look like in this ${trackLabel.toLowerCase()} role after the first quarter?`,
    `What's the biggest challenge someone in this seat at ${co} runs into?`,
    "How is performance actually measured here, beyond the job description?",
    "What made the last person in this role succeed or struggle?",
    "What's changed about this team's priorities in the last six months?",
  ];

  return { fitSummary, gaps, questions, askThem };
}
